# Use the official Python image from the Docker Hub
FROM python:3.11-slim

# Set the working directory
WORKDIR /instance

# Create the database file
RUN touch mydatabase.db

# Expose the port for the database (if needed)
EXPOSE 5432

# Command to keep the container running
CMD ["tail", "-f", "/dev/null"]