services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  rqworker:
    build:
      context: .
      dockerfile: worker.Dockerfile
    volumes:
      - ./instance:/app/instance
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    command: rq worker --with-scheduler
